- name: upgrade all packages
  yum:
    name: "*"
    state: latest
    update_cache: true
  register: yum

- name: Generate list of updated packages
  shell: rpm -qa --last | grep "$(date +%a\ %d\ %b\ %Y)" |cut -f 1 -d " "
  register: result
  when: yum.changed

- name: Show list of updated packages
  debug: msg="{{ result.stdout_lines }}"
  when: yum.changed
